name: "Autobuild deb"

on:
  push:
    branches:
      - "autobuild_linux"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: "Build package"
        run: cd distributions; sudo ./build-debian-package-auto.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            *.deb
